[package]
name = "tokio-tungstenite"
description = "Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation"
categories = ["web-programming::websocket", "network-programming", "asynchronous", "concurrency"]
keywords = ["websocket", "io", "web"]
authors = ["Daniel Abramov <dabramov@snapview.de>", "Alexey Galakhov <agalakhov@snapview.de>"]
license = "MIT"
homepage = "https://github.com/snapview/tokio-tungstenite"
documentation = "https://docs.rs/tokio-tungstenite/0.9.0"
repository = "https://github.com/snapview/tokio-tungstenite"
version = "0.10.0-alpha.1"
edition = "2018"

[features]
default = ["connect"]
connect = ["stream"]
tls = ["native-tls", "stream", "tungstenite/tls"]
stream = ["bytes"]

[dependencies]
log = "0.4"
futures = "0.3"
pin-project = "0.4"
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "master", features = ["full"] }

[dependencies.tungstenite]
version = "0.9.2"
default-features = false

[dependencies.bytes]
optional = true
version = "0.4.8"

[dependencies.native-tls]
optional = true
version = "0.2.0"

#[dependencies.tokio-tls]
#optional = true
#git = "https://github.com/tokio-rs/tokio.git"
#branch = "master"

[dev-dependencies]
url = "2.0.0"
env_logger = "0.6"
